platform: linux
image_resource:
  type: docker-image
  source:
    repository: alpine
    tag: "3.6"
inputs:
- name: version
outputs:
- name: output
run:
  path: sh
  args:
  - -exuc
  - |
    apk --update add jq
    jq -n '{
      "KUBERNETES_VERSION": $version
    }' --arg version "$(cat version/version)" > output/build-args-file
