
# ci/pipeline.yml
#
# DO NOT MAKE CHANGES TO THIS FILE. Instead, modify ci/pipeline.yml.erb and
# execute build-pipeline-yml.
#
# created: 2019-06-21T05:05:12+00:00
#
resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource

- name: file-url
  type: docker-image
  source:
    repository: pivotalservices/concourse-curl-resource
    tag: latest

resources:
- name: ubuntu-18.04
  type: docker-image
  source:
    repository: ubuntu
    tag: "18.04"

- name: kubernetes-resource
  type: git
  source:
    uri: git://github.com/zlabjp/kubernetes-resource.git
    branch: master

- name: kubernetes-resource-release
  type: git
  source:
    uri: git://github.com/zlabjp/kubernetes-resource.git
    branch: master
    tag_filter: v*

- name: notify
  type: slack-notification
  source:
    url: ((slack-url))


- name: kubernetes-resource-image-1.13
  type: docker-image
  source:
    repository: zlabjp/kubernetes-resource
    tag: "1.13"
    username: ((docker-username))
    password: ((docker-password))

- name: kubernetes-resource-image-1.14
  type: docker-image
  source:
    repository: zlabjp/kubernetes-resource
    tag: "1.14"
    username: ((docker-username))
    password: ((docker-password))

- name: kubernetes-resource-image-1.15
  type: docker-image
  source:
    repository: zlabjp/kubernetes-resource
    tag: "1.15"
    username: ((docker-username))
    password: ((docker-password))

- name: kubernetes-resource-image-latest
  type: docker-image
  source:
    repository: zlabjp/kubernetes-resource
    tag: "latest"
    username: ((docker-username))
    password: ((docker-password))


- name: kubernetes-resource-image-edge
  type: docker-image
  source:
    repository: zlabjp/kubernetes-resource
    tag: edge
    username: ((docker-username))
    password: ((docker-password))


- name: stable-1.13
  type: file-url
  source:
    url: https://storage.googleapis.com/kubernetes-release/release/stable-1.13.txt
    filename: version

- name: stable-1.14
  type: file-url
  source:
    url: https://storage.googleapis.com/kubernetes-release/release/stable-1.14.txt
    filename: version

- name: stable-1.15
  type: file-url
  source:
    url: https://storage.googleapis.com/kubernetes-release/release/stable-1.15.txt
    filename: version

- name: latest
  type: file-url
  source:
    url: https://storage.googleapis.com/kubernetes-release/release/latest.txt
    filename: version


jobs:
- name: build-kubernetes-resource-image-edge
  public: true
  serial: true
  plan:
  - do:
    - aggregate:
      - get: kubernetes-resource
        trigger: true
      - get: ubuntu-18.04
        params: {save: true}
        trigger: true
      - get: latest
        trigger: true
    - task: build-build-args-file
      file: kubernetes-resource/ci/tasks/build-build-args-file.yml
      input_mapping: {version: latest}
    - put: kubernetes-resource-image-edge
      params:
        build: kubernetes-resource
        load_base: ubuntu-18.04
        build_args_file: output/build-args-file
    on_success:
      put: notify
      params:
        channel: ((slack-success-channel))
        username: concourse / kubernetes-resource-image-edge
        icon_emoji: ":dancing-penguin:"
        text: |
          Success! $ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
    on_failure:
      put: notify
      params:
        channel: ((slack-failure-channel))
        username: concourse / kubernetes-resource:edge
        icon_emoji: ":rage:"
        text: |
          Failure! $ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME


- name: build-kubernetes-resource-image-1.13
  public: true
  serial: true
  plan:
  - do:
    - aggregate:
      - get: kubernetes-resource-release
        trigger: true
      - get: ubuntu-18.04
        params: {save: true}
        trigger: true
      - get: stable-1.13
        trigger: true
    - task: build-build-args-file
      file: kubernetes-resource-release/ci/tasks/build-build-args-file.yml
      input_mapping: {version: stable-1.13}
    - put: kubernetes-resource-image-1.13
      params:
        build: kubernetes-resource-release
        load_base: ubuntu-18.04
        build_args_file: output/build-args-file
    on_success:
      put: notify
      params:
        channel: ((slack-success-channel))
        username: concourse / kubernetes-resource-image-1.13
        icon_emoji: ":dancing-penguin:"
        text: |
          Success! $ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
    on_failure:
      put: notify
      params:
        channel: ((slack-failure-channel))
        username: concourse / kubernetes-resource-image-1.13
        icon_emoji: ":rage:"
        text: |
          Failure! $ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME

- name: build-kubernetes-resource-image-1.14
  public: true
  serial: true
  plan:
  - do:
    - aggregate:
      - get: kubernetes-resource-release
        trigger: true
      - get: ubuntu-18.04
        params: {save: true}
        trigger: true
      - get: stable-1.14
        trigger: true
    - task: build-build-args-file
      file: kubernetes-resource-release/ci/tasks/build-build-args-file.yml
      input_mapping: {version: stable-1.14}
    - put: kubernetes-resource-image-1.14
      params:
        build: kubernetes-resource-release
        load_base: ubuntu-18.04
        build_args_file: output/build-args-file
    on_success:
      put: notify
      params:
        channel: ((slack-success-channel))
        username: concourse / kubernetes-resource-image-1.14
        icon_emoji: ":dancing-penguin:"
        text: |
          Success! $ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
    on_failure:
      put: notify
      params:
        channel: ((slack-failure-channel))
        username: concourse / kubernetes-resource-image-1.14
        icon_emoji: ":rage:"
        text: |
          Failure! $ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME

- name: build-kubernetes-resource-image-1.15
  public: true
  serial: true
  plan:
  - do:
    - aggregate:
      - get: kubernetes-resource-release
        trigger: true
      - get: ubuntu-18.04
        params: {save: true}
        trigger: true
      - get: stable-1.15
        trigger: true
    - task: build-build-args-file
      file: kubernetes-resource-release/ci/tasks/build-build-args-file.yml
      input_mapping: {version: stable-1.15}
    - put: kubernetes-resource-image-1.15
      params:
        build: kubernetes-resource-release
        load_base: ubuntu-18.04
        build_args_file: output/build-args-file
    on_success:
      put: notify
      params:
        channel: ((slack-success-channel))
        username: concourse / kubernetes-resource-image-1.15
        icon_emoji: ":dancing-penguin:"
        text: |
          Success! $ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
    on_failure:
      put: notify
      params:
        channel: ((slack-failure-channel))
        username: concourse / kubernetes-resource-image-1.15
        icon_emoji: ":rage:"
        text: |
          Failure! $ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME

- name: build-kubernetes-resource-image-latest
  public: true
  serial: true
  plan:
  - do:
    - aggregate:
      - get: kubernetes-resource-release
        trigger: true
      - get: ubuntu-18.04
        params: {save: true}
        trigger: true
      - get: latest
        trigger: true
    - task: build-build-args-file
      file: kubernetes-resource-release/ci/tasks/build-build-args-file.yml
      input_mapping: {version: latest}
    - put: kubernetes-resource-image-latest
      params:
        build: kubernetes-resource-release
        load_base: ubuntu-18.04
        build_args_file: output/build-args-file
    on_success:
      put: notify
      params:
        channel: ((slack-success-channel))
        username: concourse / kubernetes-resource-image-latest
        icon_emoji: ":dancing-penguin:"
        text: |
          Success! $ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
    on_failure:
      put: notify
      params:
        channel: ((slack-failure-channel))
        username: concourse / kubernetes-resource-image-latest
        icon_emoji: ":rage:"
        text: |
          Failure! $ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME

